### ISSUE TITLE
In index.html file, add explanations to any line of code as a comment line 

### ISSUE THREAD

**Issue by SouravInsights** [EmishaCommunity/Demo-Portfolio-Website#6]
## What is a comment line?
In basic terms, comment lines are not visible in the web page. We use comment lines to explain about the code.
## How to add a comment line:
- Comments are designated by the tags `<!-- and -->.`  
- Anything that you add in between `<!-- and -->` it will become a comment line.. 
> **Note:** Try adding some explanation to at least one html tag as a comment line.

**Comment by AdrianJVillalobos** [comment]
Is this issue still active? I would like to take this at @NovaHelm

**Comment by NAMAN9JAIN** [comment]
Can I work on it too, as I am also trying to build a github portfolio for myself.

**Comment by mfonism** [comment]
Hi @SouravInsights,

Is this issue still open for Hacktoberfest 2020?

I organize a group of lifelong learners in my local community, and this would be a perfect activity to work on (and get rewarded for, with swags).

**Comment by kashishvir** [comment]
I believe it will help beginners to contribute in open source. :)
Added comments to explain your code, which can help you when you edit the source code at a later date. This is especially useful if you have a lot of code.
Hope you like my work, Thank you.

**Comment by Anshikagoel11** [comment]
please asssign me this if it still open for 2024

**Comment by SouravInsights** [comment]
> please asssign me this if it still open for 2024

hey @Anshikagoel11 it's not open actually, i just closed it.. but I'll try to find/assign some other issues if you are interested!!
